INSERT INTO public.problems (id, title, difficulty, tags, acceptance, description, examples, constraints, editorial) VALUES
(1, 'Two Sum', 'Easy', '{"Array","Hash Table"}', 49.1, 'Given an array of integers <code>nums</code> and an integer <code>target</code>, return indices of the two numbers such that they add up to <code>target</code>. You may assume that each input would have exactly one solution, and you may not use the same element twice.', '[{"input":"nums = [2,7,11,15], target = 9","output":"[0,1]","explanation":"Because nums[0] + nums[1] == 9, we return [0, 1]."},{"input":"nums = [3,2,4], target = 6","output":"[1,2]","explanation":"Because nums[1] + nums[2] == 6, we return [1, 2]."}]', '{"2 <= nums.length <= 10^4","-10^9 <= nums[i] <= 10^9","-10^9 <= target <= 10^9","Only one valid answer exists."}', 'Use a hash map to store each number and its index. For each element, check if target - element exists in the map.'),
(2, 'Add Two Numbers', 'Medium', '{"Linked List","Math","Recursion"}', 40.2, 'You are given two non-empty linked lists representing two non-negative integers. The digits are stored in reverse order, and each of their nodes contains a single digit. Add the two numbers and return the sum as a linked list.', '[{"input":"l1 = [2,4,3], l2 = [5,6,4]","output":"[7,0,8]","explanation":"342 + 465 = 807."}]', '{"The number of nodes in each linked list is in the range [1, 100].","0 <= Node.val <= 9"}', 'Simulate the addition digit by digit, keeping track of carry.'),
(3, 'Longest Substring Without Repeating Characters', 'Medium', '{"Hash Table","String","Sliding Window"}', 33.8, 'Given a string <code>s</code>, find the length of the longest substring without repeating characters.', '[{"input":"s = \"abcabcbb\"","output":"3","explanation":"The answer is \"abc\", with the length of 3."},{"input":"s = \"bbbbb\"","output":"1","explanation":"The answer is \"b\", with the length of 1."}]', '{"0 <= s.length <= 5 * 10^4","s consists of English letters, digits, symbols and spaces."}', 'Use a sliding window with a set to track characters in the current window.'),
(4, 'Median of Two Sorted Arrays', 'Hard', '{"Array","Binary Search","Divide and Conquer"}', 36.1, 'Given two sorted arrays <code>nums1</code> and <code>nums2</code> of size <code>m</code> and <code>n</code> respectively, return the median of the two sorted arrays. The overall run time complexity should be O(log (m+n)).', '[{"input":"nums1 = [1,3], nums2 = [2]","output":"2.00000","explanation":"merged array = [1,2,3] and median is 2."}]', '{"nums1.length == m","nums2.length == n","0 <= m <= 1000","0 <= n <= 1000"}', 'Binary search on the smaller array to find the correct partition.'),
(5, 'Longest Palindromic Substring', 'Medium', '{"String","Dynamic Programming"}', 32.4, 'Given a string <code>s</code>, return the longest palindromic substring in <code>s</code>.', '[{"input":"s = \"babad\"","output":"\"bab\"","explanation":"\"aba\" is also a valid answer."}]', '{"1 <= s.length <= 1000","s consist of only digits and English letters."}', 'Expand around center for each character and character pair.'),
(6, 'Valid Parentheses', 'Easy', '{"String","Stack"}', 40.7, 'Given a string <code>s</code> containing just the characters ''('', '')'', ''{'', ''}'', ''['' and '']'', determine if the input string is valid.', '[{"input":"s = \"()\"","output":"true"},{"input":"s = \"()[]{}\"","output":"true"},{"input":"s = \"(]\"","output":"false"}]', '{"1 <= s.length <= 10^4","s consists of parentheses only ''()[]{}''."}', 'Use a stack. Push opening brackets, pop and match for closing brackets.'),
(7, 'Merge Two Sorted Lists', 'Easy', '{"Linked List","Recursion"}', 61.3, 'You are given the heads of two sorted linked lists <code>list1</code> and <code>list2</code>. Merge the two lists into one sorted list and return the head of the merged linked list.', '[{"input":"list1 = [1,2,4], list2 = [1,3,4]","output":"[1,1,2,3,4,4]"}]', '{"The number of nodes in both lists is in the range [0, 50].","-100 <= Node.val <= 100"}', 'Recursively or iteratively compare heads and build the merged list.'),
(8, 'Maximum Subarray', 'Medium', '{"Array","Dynamic Programming","Divide and Conquer"}', 49.6, 'Given an integer array <code>nums</code>, find the subarray with the largest sum, and return its sum.', '[{"input":"nums = [-2,1,-3,4,-1,2,1,-5,4]","output":"6","explanation":"The subarray [4,-1,2,1] has the largest sum 6."}]', '{"1 <= nums.length <= 10^5","-10^4 <= nums[i] <= 10^4"}', 'Kadane''s algorithm: track current sum and max sum.'),
(9, 'Binary Tree Level Order Traversal', 'Medium', '{"Tree","BFS","Binary Tree"}', 64.2, 'Given the <code>root</code> of a binary tree, return the level order traversal of its nodes'' values (i.e., from left to right, level by level).', '[{"input":"root = [3,9,20,null,null,15,7]","output":"[[3],[9,20],[15,7]]"}]', '{"The number of nodes in the tree is in the range [0, 2000].","-1000 <= Node.val <= 1000"}', 'Use a queue (BFS). Process nodes level by level.'),
(10, 'Word Search', 'Hard', '{"Array","Backtracking","Matrix"}', 39.8, 'Given an <code>m x n</code> grid of characters <code>board</code> and a string <code>word</code>, return <code>true</code> if <code>word</code> exists in the grid.', '[{"input":"board = [[\"A\",\"B\",\"C\",\"E\"],[\"S\",\"F\",\"C\",\"S\"],[\"A\",\"D\",\"E\",\"E\"]], word = \"ABCCED\"","output":"true"}]', '{"m == board.length","n = board[i].length","1 <= m, n <= 6","1 <= word.length <= 15"}', 'DFS with backtracking from each cell.'),
(11, 'Climbing Stairs', 'Easy', '{"Math","Dynamic Programming","Memoization"}', 51.8, 'You are climbing a staircase. It takes <code>n</code> steps to reach the top. Each time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?', '[{"input":"n = 2","output":"2","explanation":"1+1, 2"},{"input":"n = 3","output":"3","explanation":"1+1+1, 1+2, 2+1"}]', '{"1 <= n <= 45"}', 'This is essentially Fibonacci. dp[i] = dp[i-1] + dp[i-2].'),
(12, 'Number of Islands', 'Medium', '{"Array","DFS","BFS","Matrix","Union Find"}', 55.3, 'Given an <code>m x n</code> 2D binary grid which represents a map of ''1''s (land) and ''0''s (water), return the number of islands.', '[{"input":"grid = [[\"1\",\"1\",\"1\",\"1\",\"0\"],[\"1\",\"1\",\"0\",\"1\",\"0\"],[\"1\",\"1\",\"0\",\"0\",\"0\"],[\"0\",\"0\",\"0\",\"0\",\"0\"]]","output":"1"}]', '{"m == grid.length","n == grid[i].length","1 <= m, n <= 300"}', 'DFS/BFS from each unvisited land cell, marking visited cells.')
ON CONFLICT (id) DO NOTHING;